FORMAT: 1A
HOST: http://factory.zone/api/v1/

# Notice API

Provides services for Company features 

## Notices [project/{project_id}/notice{?page,size}]

+ Parameters
    + project_id(required, number,`2`)

### Create Notice [POST]

+ Request (application/json)

    +   Headers 
            
            Authorization: Basic dXNlcjpwYXNzd29yZA==
            x-api-version: 1.0
    + Body
            
            {
                "title":"Launch in 24hrs"
                "decription": "We launch project ARA in 24hrs"
                "noticeType":"Launch"
            }
            
+ Response 201 (application/json)

     + Headers 
        
            Location: /notice/:id
    
    + Body
    
            {
                "company_id":1
                "project_id":2
                "notice_id":2
                "title":"Launch in 24hrs"
                "noticeType":"Launch"
                "decription": "We launch project ARA in 24hrs"
                "createdAt":"2017-6-21 08:12:05"

            }
            
### List Notices [GET]

+ Parameters
    + page(required, number,`1`)...'page' number
    + size(required, number, `10`)... page 'size'

+ Request

    +   Headers 
            
            Authorization: Basic dXNlcjpwYXNzd29yZA==
            x-api-version: 1.0
    
+ Response 200 (application/json)
 
    + Headers
        
            ETag : "euyfewuyfvew76f7"
            cache-control: max-age=600

    + Body
            
            {
                                    
                "page":
                {
                    "number":1,
                    "size":10 
                    "totalPages": 20
                },
                "notices":
                [
                    {
                        "notice_id":2
                        "company_id":1
                        "title":"Launch in 24hrs"
                        "noticeType":"Launch"
                        "decription": "We launch project ARA in 24hrs"
                        "createdAt":"2017-6-21 08:12:05"
                    },
                    {
                        "notice_id":4
                        "company_id":2
                        "title":"Waymo Discontinued"
                        "noticeType":"Discontinued"
                        "decription": "Project Waymo has been discontinued"
                        "createdAt":"2017-6-21 08:12:05"
                    }
                    
                ]
            }

## Notice [project/{project_id}/notice/{notice_id}]
+ Parameters
    + project_id(required, number,`1`)

### View Notice [GET]
+ Request

    +   Headers 
            
            Authorization: Basic dXNlcjpwYXNzd29yZA==
            x-api-version: 1.0
    
+ Response 200 (application/json)
 
    + Headers
        
            ETag : "euyfewuyfvew76f7"
            cache-control: max-age=600

    + Body
    
            {
                "company_id":1
                "department_id":1
                "company_id":4
                "user_id":5
                "project_id":2
                "notice_id":2
                "title":"Launch in 24hrs"
                "noticeType":"Launch"
                "decription": "We launch project ARA in 24hrs"
                "createdAt":"2017-6-21 08:12:05"
            }

### Edit Notice [PUT]
+ Request (application/json)

    +   Headers 
            
            Authorization: Basic dXNlcjpwYXNzd29yZA==
            x-api-version: 1.0
    + Body
            
            {
                "company_id":1
                "deparment_id":3
                "project_id":2
                "user_id":23
                "notice_id":2
                "title":"Launch in 24hrs"
                "noticeType":"Launch"
                "decription": "We launch project ARA in 24hrs"
                "createdAt":"2017-6-21 08:12:05"
            }  
+ Response 200 (application/json)

    + Headers
        
            Location: /notice:id
    
    + Body
    
            {
                "company_id":1
                "deparment_id":3
                "project_id":2
                "user_id":23
                "notice_id":2
                "title":"Launch in 12hrs"
                "noticeType":"Launch"
                "decription": "We launch project ARA in 24hrs"
                "createdAt":"2017-6-21 08:12:05"
            }

### Delete Notice [DELETE]
+ Response 204